replicaCount: 1
image:
  repository: akshaykmanoj/my-django-login
  tag: latest
  pullPolicy: IfNotPresent
resources: {}
nodeSelector: {}
affinity: {}
tolerations: {}

ingress:
  enabled: false  # Set to true if you're using ingress, otherwise set to false
  # other ingress-related configuration

# Blue-Green Deployment Configuration
blueGreen:
  activeService: argo-helm  # Replace with your active service name
  previewService: argo-helm-preview  # Replace with your preview service name

# Horizontal Pod Autoscaler Configuration
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10  # Set your desired max replicas
  targetCPUUtilizationPercentage: 50  # Set your desired average CPU utilization

# Service Configuration
service:
  name: argo-helm  # Replace with your service name
  type: Nodeport
  port: 8001
  targetPort: http
  selectorApp: argo-helm  # Replace with your app label
  selectorRelease: my-argo-release  # Replace with your release name
  selectorVersion1: green  # Change to blue for blue deployment
  selectorVersion2: blue  # Change to blue for blue deployment
